// Copyright 2016 The Chromium Embedded Framework Authors. Portions copyright
// 2013 The Chromium Authors. All rights reserved. Use of this source code is
// governed by a BSD-style license that can be found in the LICENSE file.

#ifndef OSRCEFTEXTINPUTCLIENT_H
#define OSRCEFTEXTINPUTCLIENT_H
#pragma once

#import <Cocoa/Cocoa.h>

#include <string>
#include <vector>

#include "include/cef_browser.h"
#include "include/cef_render_handler.h"

// mac osr模式下面，按键会触发听写、表情等快捷指令
// https://github.com/chromiumembedded/cef/issues/3857
// 检查是否为会触发系统快捷指令的字符 (d: 听写, e: 表情, f: 全屏)
inline bool IsMacOsrShortcutChar(char16_t character) {
    return character == 'd' || character == 'e' || character == 'f';
}

// Implementation for the NSTextInputClient protocol used for enabling IME on
// mac when window rendering is disabled.

@interface OsrCefTextInputClient : NSObject <NSTextInputClient> {
 @private

    // The range of current marked text inside the whole content of the DOM node
    // being edited.
    NSRange _markedRange;

    // The current composition character range and its bounds.
    CefRange _compositionRange;
    std::vector<CefRect> _compositionBounds;

    // Represents the input-method attributes supported by this object.
    NSArray* _validAttributesForMarkedText;

    // Indicates if we are currently handling a key down event.
    BOOL _handlingKeyDown;

    // Indicates if there is any marked text.
    BOOL _hasMarkedText;

    // Indicates whether there was any marked text prior to handling
    // the current key event.
    BOOL _oldHasMarkedText;

    // Indicates if unmarkText is called or not when handling a keyboard
    // event.
    BOOL _unmarkTextCalled;

    // The selected range, cached from a message sent by the renderer.
    NSRange _selectedRange;

    // Text to be inserted which was generated by handling a key down event.
    std::string _textToBeInserted;

    // Marked text which was generated by handling a key down event.
    CefString _markedText;

    // Underline information of the |_markedText|.
    std::vector<CefCompositionUnderline> _underlines;

    // Replacement range information received from |setMarkedText:|.
    CefRange _replacementRange;

    CefRefPtr<CefBrowser> _browser;
}

@property(nonatomic, readonly) NSRange selectedRange;
@property(nonatomic) BOOL handlingKeyDown;

- (id)initWithBrowser:(CefRefPtr<CefBrowser>)browser;
- (void)detach;
- (void)HandleKeyEventBeforeTextInputClient:(NSEvent*)keyEvent;
- (void)HandleKeyEventAfterTextInputClient:(CefKeyEvent)keyEvent;
- (void)ChangeCompositionRange:(CefRange)range
              character_bounds:(const CefRenderHandler::RectList&)bounds;
- (void)cancelComposition;

@end

#endif  // OSRCEFTEXTINPUTCLIENT_H
